name: Pre-Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
      - '!v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  CreateRelease:
    name: CreateRelease
    uses: EncoreDigitalGroup/.github/.github/workflows/createPreRelease.yml@v1
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
      generate_release_notes: true
      is_draft: false
      pre_release: true