name: Build Documentation
on:
  push:
    paths:
    - 'webHelpIN2-all.zip'
  workflow_dispatch:
  
jobs:
  Extract:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: 'Extract Docs'
        run: |
          rm -rf ./pages
          rm -rf ./docs
          unzip webHelpIN2-all.zip -d ./docs
          rm webHelpIN2-all.zip
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions"
          git add .
          git commit -m "Build Documentation"
          git push origin docs              
