name: GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  GitHubPages:
    name: GitHubPages
    uses: EncoreDigitalGroup/.github/.github/workflows/deplotGitHubPages.yml@v1
    permissions:
      contents: write
      pages: write
      id-token: write
