name: GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  GitHubPages:
    name: GitHubPages
    uses: EncoreDigitalGroup/.github/.github/workflows/deploy-github-pages.yml@main
    permissions:
      contents: read
      pages: write
      id-token: write
