name: DirectorySync

on:
  push:
    branches:
      - main
    paths:
      - docs/**/*
  workflow_dispatch:

jobs:
  DirectorySync:
    uses: EncoreDigitalGroup/.github/.github/workflows/directorySync.yml@v1
    with:
      source: 'docs/'
      targetRepo: 'encoredigitalgroup/docs.encoredigitalgroup.com'
      targetDirectory: 'documentationImport/PlanningCenter-PHP-SDK'
    secrets:
      token: ${{ secrets.GH_GENERAL_ACCESS_TOKEN }}
